### ISSUE TITLE
[BUG] - undefined (reading 'registrations')

### ISSUE THREAD

**Issue by koushikbuiltin** [elaichenkov/playwright-zephyr#19]
Hi, I am facing the below issue.

Configuration:
```
  reporter: [
    [
      "playwright-zephyr",
      {
        host: "https://project.atlassian.net/",
        authorizationToken:"token",
        projectKey: "projectKEY",
      },
    ],
  ],
```
Error message:
Error in reporter TypeError: Cannot read properties of undefined (reading 'registrations')

Playwright version -     "@playwright/test": "^1.31.2",

**Comment by armin-mehinovic** [comment]
Having the same issue!

**Comment by benweese** [comment]
```
Error in reporter TypeError: Cannot read properties of undefined (reading 'registrations')
    at ZephyrReporter.onTestEnd (/Users/benweese/Development/e2e-testing/node_modules/playwright-zephyr/lib/src/index.js:32:44)
    at /Users/benweese/Development/e2e-testing/node_modules/@playwright/test/lib/reporters/multiplexer.js:91:131
    at wrap (/Users/benweese/Development/e2e-testing/node_modules/@playwright/test/lib/reporters/multiplexer.js:137:5)
    at Multiplexer.onTestEnd (/Users/benweese/Development/e2e-testing/node_modules/@playwright/test/lib/reporters/multiplexer.js:89:45)
    at Dispatcher._reportTestEnd (/Users/benweese/Development/e2e-testing/node_modules/@playwright/test/lib/runner/dispatcher.js:513:159)
    at WorkerHost.onTestEnd (/Users/benweese/Development/e2e-testing/node_modules/@playwright/test/lib/runner/dispatcher.js:235:12)
    at WorkerHost.emit (node:events:512:28)
    at ChildProcess.<anonymous> (/Users/benweese/Development/e2e-testing/node_modules/@playwright/test/lib/runner/processHost.js:93:16)
    at ChildProcess.emit (node:events:512:28)
    at emit (node:internal/child_process:944:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
There are no tests with such /\[(.*?)\]/ key pattern
```

The last comment says there is no test with the pattern [T12]. I assure you all of them have it.

**Comment by dylanz** [comment]
@benweese same issue here

**Comment by antoniojg** [comment]
Still nothing on this issue? Anyone figure out a workaround or what the issue is?

**Comment by nemanjajeremic** [comment]
Having the same issue.

**Comment by abhishek-trantorinc** [comment]
same issue, is there any fix?

**Comment by cspell0012** [comment]
Same issue here.
